apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-ve20-k8s-2-my-blog
  namespace: my-blog
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ve20-k8s-2-my-blog
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: ve20-k8s-2-my-blog
